name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - dev*

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies with CI
        run: npm ci

      - name: Build TS
        run: npm run build

      - name: Run tests
        run: npm test
      
      - name: Set Version
        run: node setVersion.js

      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Node Tests 
          path: test-report.xml
          reporter: java-junit

      - name: Build sample projects
        run: |
          for dir in ./test-agents/*/; do
            echo "Building $dir"
             (cd "$dir" && npm i && npm run build)
          done
